---

- name: Install rbenv
  homebrew: name=rbenv state=latest

- name: Install ruby-build
  homebrew: name=ruby-build state=latest

- name: Install Ruby ({{ homebrew_rbenv.ruby_version }})
  shell: >
    eval "$(rbenv init -)";
    rbenv install {{ homebrew_rbenv.ruby_version }}
    creates=~/.rbenv/versions/{{ homebrew_rbenv.ruby_version }}
  environment:
    PATH: $PATH:{{ homebrew_brew_bin_path }}

- name: Install Bundler
  gem: name=bundler state=latest user_install=no executable=~/.rbenv/shims/gem
